/**
 * AgroGlobalDex - happy-path PoC tests.
 *
 * Coverage:
 *  1. initialize marketplace
 *  2. register a Grain asset
 *  3. mint tokens to the issuer
 *  4. attempt buy WITHOUT KYC -> must fail
 *  5. KYC the buyer
 *  6. list + buy with KYC -> must succeed
 *  7. redeem (burn) some tokens
 *
 * Run with: `anchor test`
 */

import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import {
  PublicKey,
  Keypair,
  SystemProgram,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  TOKEN_2022_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  getAssociatedTokenAddressSync,
} from "@solana/spl-token";
import { assert } from "chai";

// The IDL type is generated by `anchor build` into target/types.
// For the PoC we type the program loosely.
type Agroglobaldex = any;

const MARKETPLACE_SEED = Buffer.from("marketplace");
const COMPLIANCE_AUTHORITY_SEED = Buffer.from("compliance_authority");
const ASSET_REGISTRY_SEED = Buffer.from("asset_registry");
const ASSET_MINT_SEED = Buffer.from("asset_mint");
const COMPLIANCE_RECORD_SEED = Buffer.from("compliance_record");
const LISTING_SEED = Buffer.from("listing");

describe("agroglobaldex", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const program = anchor.workspace.Agroglobaldex as Program<Agroglobaldex>;

  // Actors.
  const authority = provider.wallet; // Marketplace + compliance authority.
  const issuer = Keypair.generate();
  const buyer = Keypair.generate();

  // PDAs.
  let marketplacePda: PublicKey;
  let complianceAuthorityPda: PublicKey;
  let assetRegistryPda: PublicKey;
  let assetMintPda: PublicKey;
  let buyerCompliancePda: PublicKey;
  let listingPda: PublicKey;

  before(async () => {
    // Airdrop SOL to issuer & buyer so they can pay rent + fees.
    for (const kp of [issuer, buyer]) {
      const sig = await provider.connection.requestAirdrop(
        kp.publicKey,
        5 * LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
    }

    [marketplacePda] = PublicKey.findProgramAddressSync(
      [MARKETPLACE_SEED, authority.publicKey.toBuffer()],
      program.programId
    );
    [complianceAuthorityPda] = PublicKey.findProgramAddressSync(
      [COMPLIANCE_AUTHORITY_SEED, marketplacePda.toBuffer()],
      program.programId
    );
  });

  it("initializes the marketplace", async () => {
    await program.methods
      .initialize(50) // 0.5% fee
      .accounts({
        authority: authority.publicKey,
        marketplace: marketplacePda,
        complianceAuthority: complianceAuthorityPda,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const mp = await program.account.marketplace.fetch(marketplacePda);
    assert.equal(mp.feeBps, 50);
    assert.equal(mp.assetCount.toString(), "0");
  });

  it("registers a Grain asset", async () => {
    const mp = await program.account.marketplace.fetch(marketplacePda);
    const indexBytes = Buffer.alloc(8);
    indexBytes.writeBigUInt64LE(BigInt(mp.assetCount.toString()));

    [assetRegistryPda] = PublicKey.findProgramAddressSync(
      [
        ASSET_REGISTRY_SEED,
        marketplacePda.toBuffer(),
        issuer.publicKey.toBuffer(),
        indexBytes,
      ],
      program.programId
    );
    [assetMintPda] = PublicKey.findProgramAddressSync(
      [ASSET_MINT_SEED, assetRegistryPda.toBuffer()],
      program.programId
    );

    const attestation = Array.from(Buffer.alloc(32, 1)); // dummy hash
    const assetClass = {
      grain: { kind: { soy: {} }, tons: new BN(1000) },
    };

    await program.methods
      .registerAsset(
        assetClass,
        new BN(1_000_000_000), // 1000 tons * 1e6 base units
        attestation,
        "ipfs://Qm.../whitepaper.pdf",
        "ipfs://Qm.../metadata.json"
      )
      .accounts({
        issuer: issuer.publicKey,
        marketplace: marketplacePda,
        assetRegistry: assetRegistryPda,
        mint: assetMintPda,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .signers([issuer])
      .rpc();

    const reg = await program.account.assetRegistry.fetch(assetRegistryPda);
    assert.equal(reg.issuer.toBase58(), issuer.publicKey.toBase58());
    assert.equal(reg.totalSupply.toString(), "1000000000");
    assert.equal(reg.redeemable, true);
  });

  it("mints tokens to the issuer", async () => {
    const issuerAta = getAssociatedTokenAddressSync(
      assetMintPda,
      issuer.publicKey,
      false,
      TOKEN_2022_PROGRAM_ID
    );

    await program.methods
      .mintToken(new BN(500_000_000))
      .accounts({
        issuer: issuer.publicKey,
        assetRegistry: assetRegistryPda,
        mint: assetMintPda,
        issuerTokenAccount: issuerAta,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .signers([issuer])
      .rpc();

    const reg = await program.account.assetRegistry.fetch(assetRegistryPda);
    assert.equal(reg.mintedSupply.toString(), "500000000");
  });

  it("lists tokens on the marketplace", async () => {
    [listingPda] = PublicKey.findProgramAddressSync(
      [LISTING_SEED, assetRegistryPda.toBuffer(), issuer.publicKey.toBuffer()],
      program.programId
    );
    const sellerAta = getAssociatedTokenAddressSync(
      assetMintPda,
      issuer.publicKey,
      false,
      TOKEN_2022_PROGRAM_ID
    );
    const escrow = getAssociatedTokenAddressSync(
      assetMintPda,
      listingPda,
      true,
      TOKEN_2022_PROGRAM_ID
    );

    await program.methods
      .listAsset(new BN(1_000), new BN(100_000_000)) // 1000 lamports per unit, 100 tons
      .accounts({
        seller: issuer.publicKey,
        marketplace: marketplacePda,
        assetRegistry: assetRegistryPda,
        mint: assetMintPda,
        sellerTokenAccount: sellerAta,
        listing: listingPda,
        escrow,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .signers([issuer])
      .rpc();

    const listing = await program.account.marketplaceListing.fetch(listingPda);
    assert.equal(listing.remaining.toString(), "100000000");
    assert.equal(listing.active, true);
  });

  it("rejects a buy from a wallet without a compliance record", async () => {
    [buyerCompliancePda] = PublicKey.findProgramAddressSync(
      [
        COMPLIANCE_RECORD_SEED,
        marketplacePda.toBuffer(),
        buyer.publicKey.toBuffer(),
      ],
      program.programId
    );
    const buyerAta = getAssociatedTokenAddressSync(
      assetMintPda,
      buyer.publicKey,
      false,
      TOKEN_2022_PROGRAM_ID
    );
    const escrow = getAssociatedTokenAddressSync(
      assetMintPda,
      listingPda,
      true,
      TOKEN_2022_PROGRAM_ID
    );

    let threw = false;
    try {
      await program.methods
        .buyAsset(new BN(1_000_000))
        .accounts({
          buyer: buyer.publicKey,
          marketplace: marketplacePda,
          feeRecipient: authority.publicKey,
          assetRegistry: assetRegistryPda,
          listing: listingPda,
          escrow,
          seller: issuer.publicKey,
          mint: assetMintPda,
          buyerTokenAccount: buyerAta,
          buyerCompliance: buyerCompliancePda,
          tokenProgram: TOKEN_2022_PROGRAM_ID,
          associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
        })
        .signers([buyer])
        .rpc();
    } catch (e) {
      threw = true;
    }
    assert.isTrue(threw, "buy without compliance record must fail");
  });

  it("KYCs the buyer", async () => {
    await program.methods
      .updateKyc(true, [68, 69], false) // "DE"
      .accounts({
        complianceSigner: authority.publicKey,
        marketplace: marketplacePda,
        complianceAuthority: complianceAuthorityPda,
        wallet: buyer.publicKey,
        complianceRecord: buyerCompliancePda,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const rec = await program.account.complianceRecord.fetch(buyerCompliancePda);
    assert.equal(rec.kycVerified, true);
  });

  it("allows the KYCed buyer to purchase", async () => {
    const buyerAta = getAssociatedTokenAddressSync(
      assetMintPda,
      buyer.publicKey,
      false,
      TOKEN_2022_PROGRAM_ID
    );
    const escrow = getAssociatedTokenAddressSync(
      assetMintPda,
      listingPda,
      true,
      TOKEN_2022_PROGRAM_ID
    );

    await program.methods
      .buyAsset(new BN(1_000_000))
      .accounts({
        buyer: buyer.publicKey,
        marketplace: marketplacePda,
        feeRecipient: authority.publicKey,
        assetRegistry: assetRegistryPda,
        listing: listingPda,
        escrow,
        seller: issuer.publicKey,
        mint: assetMintPda,
        buyerTokenAccount: buyerAta,
        buyerCompliance: buyerCompliancePda,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .signers([buyer])
      .rpc();

    const listing = await program.account.marketplaceListing.fetch(listingPda);
    assert.equal(listing.remaining.toString(), "99000000");
  });

  it("redeems (burns) tokens", async () => {
    const buyerAta = getAssociatedTokenAddressSync(
      assetMintPda,
      buyer.publicKey,
      false,
      TOKEN_2022_PROGRAM_ID
    );

    await program.methods
      .redeem(new BN(500_000))
      .accounts({
        holder: buyer.publicKey,
        assetRegistry: assetRegistryPda,
        mint: assetMintPda,
        holderTokenAccount: buyerAta,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
      })
      .signers([buyer])
      .rpc();
    // Burn succeeded if no exception thrown.
  });
});
